name: Build /test 

on:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Test
        run: node --test

  bump-version-and-publish:
    needs: build-test
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ github.ref }}
      - name: Set the git user
        id: set-git-user
        run: |
          git config --global user.name ${{ github.event.pusher.name }}
          git config --global user.email ${{ github.event.pusher.email }}
      - name: Automated version bump
        uses: phips28/gh-action-bump-version@master
        with:
          commit-message: 'CI: Bump version to {{version}}'
          tag-prefix:  'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Debug
        run: echo "bumped version"

